### ISSUE TITLE
Can & should I output two stylesheets?

### ISSUE THREAD

**Issue by davidtheclark** [sapegin/grunt-webfont#43]
I want to create an SCSS stylesheet that incorporates mixins and/or extends. I do not want to write vanilla CSS classes into this stylesheet because I don't need them in my project and don't want unnecessary bulk in my stylesheet. However, in order for the demo HTML template to work, I will need vanilla CSS classes that can be plugged into the HTML document, without precompiling.

Maybe the way to do this is to be able to output multiple stylesheets based on different templates, so I can output one vanilla CSS stylesheet that is loaded into my demo HTML but ignored by the project; and an SCSS stylesheet for the actual project.

Or maybe there's a better way?

Here is the template I'm using: https://gist.github.com/MisterGrumpyPants/6244560

**Comment by xPetrus** [comment]
I know this is an old post but this may help someone else. You can also download the adobe scout app which is free and @import your separate .scss files into your main.css file. It's easy and I've been using it with the yeoman/grunt workflow very well.

**Comment by nicolag** [comment]
+1 @davidtheclark 
Hey @sapegin, it will be great to have stylesheet accept array, so that can give options for team members to choose using different preprocess or markup way (css), instead of having another step to compile it or change it to make it work. font custom can output multiple stylesheets as well as long as multiple templates.

**Comment by sapegin** [comment]
@nicolag Can you make such pull request?
